import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Manrope', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                surface: '#fcf9f8',
                'surface-dim': '#dcd9d9',
                'surface-bright': '#fcf9f8',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f6f3f2',
                'surface-container': '#f0eded',
                'surface-container-high': '#eae7e7',
                'surface-container-highest': '#e5e2e1',
                'on-surface': '#1b1b1c',
                'on-surface-variant': '#564241',
                'inverse-surface': '#303030',
                'inverse-on-surface': '#f3f0ef',
                outline: '#897170',
                'outline-variant': '#ddc0be',
                'surface-tint': '#a23c3e',
                primary: '#9e3a3c',
                'on-primary': '#ffffff',
                'primary-container': '#be5252',
                'on-primary-container': '#fffbff',
                'inverse-primary': '#ffb3b0',
                secondary: '#715859',
                'on-secondary': '#ffffff',
                'secondary-container': '#fcdbdb',
                'on-secondary-container': '#775e5f',
                tertiary: '#006a45',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#008558',
                'on-tertiary-container': '#f6fff6',
                error: '#ba1a1a',
                'on-error': '#ffffff',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'primary-fixed': '#ffdad8',
                'primary-fixed-dim': '#ffb3b0',
                'on-primary-fixed': '#410006',
                'on-primary-fixed-variant': '#822529',
                'secondary-fixed': '#fcdbdb',
                'secondary-fixed-dim': '#debfbf',
                'on-secondary-fixed': '#281717',
                'on-secondary-fixed-variant': '#574142',
                'tertiary-fixed': '#88f8bf',
                'tertiary-fixed-dim': '#6bdba5',
                'on-tertiary-fixed': '#002113',
                'on-tertiary-fixed-variant': '#005234',
                background: '#fcf9f8',
                'on-background': '#1b1b1c',
                'surface-variant': '#e5e2e1',
            },
            borderRadius: {
                sm: '0.25rem',
                DEFAULT: '0.5rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
                full: '9999px',
            },
            spacing: {
                base: '8px',
                xs: '4px',
                sm: '12px',
                md: '24px',
                lg: '48px',
            },
        },
    },

    plugins: [forms],
};
